version: 2.1
executors:
  default:
    working_directory: ~/catkin_ws/src
    docker:
      - image: ros:kinetic-ros-core-xenial
jobs:
  setup:
    executor:
      name: default
    steps:
      - run:
          name: Setup environment
          command: |
            source /opt/ros/${ROS_DISTRO}/setup.bash
            apt-get update -y -qq
            apt-get upgrade -y -qq
            apt-get install -y -qq python-pip
            pip install -q catkin_tools
            cd ~/catkin_ws
            catkin init
            catkin build
      - checkout
      - run:
          name: Install ROS dependencies
          command: |
            source ~/catkin_ws/devel/setup.bash
            rosdep install -y -i --from-paths ~/catkin_ws/src/
      - save_cache:
          key: ws-{{ .Revision }}
          paths:
            - /opt/ros/${ROS_DISTRO}/share/
            - ~/catkin_ws/
  build:
    executor:
      name: default
    steps:
      - restore_cache:
          key: ws-{{ .Revision }}
      - run:
          name: catkin build
          command: |
            catkin build --no-notify --no-status
workflows:
  version: 2
  build-test:
    jobs:
      - setup
      - build:
          requires:
            - setup
