version: 2.1
executors:
  default:
    working_directory: ~/catkin_ws/src
    docker:
      - image: ros:kinetic-ros-core-xenial
commands:
  ros-setup:
    steps:
      - checkout
      - run:
          name: Setup environment
          command: |
            source /opt/ros/${ROS_DISTRO}/setup.bash
            apt-get update -y -qq
            apt-get upgrade -y -qq
            apt-get install -y -qq python-pip
            pip install -q catkin_tools
            cd ~/catkin_ws
            catkin init
      - run:
          name: Install ROS dependencies
          command: |
            source /opt/ros/${ROS_DISTRO}/setup.bash
            rosdep install -y -i --from-paths ~/catkin_ws/src/
jobs:
  build:
    executor:
      name: default
    steps:
      - ros-setup
      - run:
          name: catkin build
          command: |
            source /opt/ros/${ROS_DISTRO}/setup.bash
            catkin build --no-notify --no-status
  roslint:
    executor:
      name: default
    steps:
      - ros-setup
      - run:
          name: roslint
          command: |
            source /opt/ros/${ROS_DISTRO}/setup.bash
            catkin build --no-notify --no-status --catkin-make-args roslint
workflows:
  version: 2
  build-test:
    jobs:
      - build
      - roslint