version: 2.1
executors:
  default:
    working_directory: ~/catkin_ws/src
    docker:
      - image: ros:kinetic-ros-core-xenial
jobs:
  build:
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: Update and install dependencies
          command: |
            apt-get update -y
            apt-get upgrade -y
            rosdep install -y -i --from-paths .
      - run:
          name: catkin_make
          command: |
            cd ~/catkin_ws
            catkin_make_isolated
